'------------------------------------------------------------------------------
' <auto-generated>
'     Tento kód byl generován nástrojem.
'     Verze modulu runtime:4.0.30319.42000
'
'     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
'     dojde-li k novému generování kódu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReferenceAgiloKontakty
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="KontaktContract", [Namespace]:="http://www.altus.cz/Altus.COM.V12.BasicContracts/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class KontaktContract
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdresaSidloField As ServiceReferenceAgiloKontakty.AdresaContract
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdresaSidloNaDokladField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CenikField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DICField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DatumNarozeniField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DodavatelField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DomenaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DopravaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DorucovaciAdresaField As ServiceReferenceAgiloKontakty.AdresaContract
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DorucovaciAdresaNaDokladField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExtendedPropertiesField() As ServiceReferenceAgiloKontakty.ExtendedPropertyContract
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FakturacniAdresaField As ServiceReferenceAgiloKontakty.AdresaContract
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Fax2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirmaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunkceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HesloField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ICField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InternetField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private JazykField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private JmenoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KamOdeselField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KategorieField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KategorieCenField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KnihaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NadrizenyKontaktIdField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NazevFirmyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NazevFirmy2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObchodniRejstrikField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OdberatelField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PlatceDPHField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Pocet1Field As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Pocet2Field As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PocetZamestnancuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PoznamkyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrihlasovaciJmenoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrijmeniField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReferentField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SablonaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SlevaField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SlevaDodavateleField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SplatnostFakturField As Short
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StavKontaktuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelefonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Telefon2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypKontaktuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypZaznamuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Udaj1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Udaj2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UrokField As Single
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ZasilatField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ZpusobUhradyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private rowguidField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private timestampField() As Byte
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdresaSidlo() As ServiceReferenceAgiloKontakty.AdresaContract
            Get
                Return Me.AdresaSidloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdresaSidloField, value) <> true) Then
                    Me.AdresaSidloField = value
                    Me.RaisePropertyChanged("AdresaSidlo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdresaSidloNaDoklad() As System.Nullable(Of Boolean)
            Get
                Return Me.AdresaSidloNaDokladField
            End Get
            Set
                If (Me.AdresaSidloNaDokladField.Equals(value) <> true) Then
                    Me.AdresaSidloNaDokladField = value
                    Me.RaisePropertyChanged("AdresaSidloNaDoklad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cenik() As String
            Get
                Return Me.CenikField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CenikField, value) <> true) Then
                    Me.CenikField = value
                    Me.RaisePropertyChanged("Cenik")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DIC() As String
            Get
                Return Me.DICField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DICField, value) <> true) Then
                    Me.DICField = value
                    Me.RaisePropertyChanged("DIC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DatumNarozeni() As Date
            Get
                Return Me.DatumNarozeniField
            End Get
            Set
                If (Me.DatumNarozeniField.Equals(value) <> true) Then
                    Me.DatumNarozeniField = value
                    Me.RaisePropertyChanged("DatumNarozeni")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Dodavatel() As Boolean
            Get
                Return Me.DodavatelField
            End Get
            Set
                If (Me.DodavatelField.Equals(value) <> true) Then
                    Me.DodavatelField = value
                    Me.RaisePropertyChanged("Dodavatel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Domena() As String
            Get
                Return Me.DomenaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DomenaField, value) <> true) Then
                    Me.DomenaField = value
                    Me.RaisePropertyChanged("Domena")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Doprava() As String
            Get
                Return Me.DopravaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DopravaField, value) <> true) Then
                    Me.DopravaField = value
                    Me.RaisePropertyChanged("Doprava")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DorucovaciAdresa() As ServiceReferenceAgiloKontakty.AdresaContract
            Get
                Return Me.DorucovaciAdresaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DorucovaciAdresaField, value) <> true) Then
                    Me.DorucovaciAdresaField = value
                    Me.RaisePropertyChanged("DorucovaciAdresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DorucovaciAdresaNaDoklad() As System.Nullable(Of Boolean)
            Get
                Return Me.DorucovaciAdresaNaDokladField
            End Get
            Set
                If (Me.DorucovaciAdresaNaDokladField.Equals(value) <> true) Then
                    Me.DorucovaciAdresaNaDokladField = value
                    Me.RaisePropertyChanged("DorucovaciAdresaNaDoklad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExtendedProperties() As ServiceReferenceAgiloKontakty.ExtendedPropertyContract()
            Get
                Return Me.ExtendedPropertiesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExtendedPropertiesField, value) <> true) Then
                    Me.ExtendedPropertiesField = value
                    Me.RaisePropertyChanged("ExtendedProperties")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FakturacniAdresa() As ServiceReferenceAgiloKontakty.AdresaContract
            Get
                Return Me.FakturacniAdresaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FakturacniAdresaField, value) <> true) Then
                    Me.FakturacniAdresaField = value
                    Me.RaisePropertyChanged("FakturacniAdresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fax() As String
            Get
                Return Me.FaxField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaxField, value) <> true) Then
                    Me.FaxField = value
                    Me.RaisePropertyChanged("Fax")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fax2() As String
            Get
                Return Me.Fax2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Fax2Field, value) <> true) Then
                    Me.Fax2Field = value
                    Me.RaisePropertyChanged("Fax2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Firma() As String
            Get
                Return Me.FirmaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirmaField, value) <> true) Then
                    Me.FirmaField = value
                    Me.RaisePropertyChanged("Firma")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Funkce() As String
            Get
                Return Me.FunkceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunkceField, value) <> true) Then
                    Me.FunkceField = value
                    Me.RaisePropertyChanged("Funkce")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Heslo() As String
            Get
                Return Me.HesloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HesloField, value) <> true) Then
                    Me.HesloField = value
                    Me.RaisePropertyChanged("Heslo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IC() As String
            Get
                Return Me.ICField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ICField, value) <> true) Then
                    Me.ICField = value
                    Me.RaisePropertyChanged("IC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Internet() As String
            Get
                Return Me.InternetField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InternetField, value) <> true) Then
                    Me.InternetField = value
                    Me.RaisePropertyChanged("Internet")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Jazyk() As String
            Get
                Return Me.JazykField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JazykField, value) <> true) Then
                    Me.JazykField = value
                    Me.RaisePropertyChanged("Jazyk")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Jmeno() As String
            Get
                Return Me.JmenoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JmenoField, value) <> true) Then
                    Me.JmenoField = value
                    Me.RaisePropertyChanged("Jmeno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property KamOdesel() As String
            Get
                Return Me.KamOdeselField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KamOdeselField, value) <> true) Then
                    Me.KamOdeselField = value
                    Me.RaisePropertyChanged("KamOdesel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Kategorie() As String
            Get
                Return Me.KategorieField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KategorieField, value) <> true) Then
                    Me.KategorieField = value
                    Me.RaisePropertyChanged("Kategorie")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property KategorieCen() As String
            Get
                Return Me.KategorieCenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KategorieCenField, value) <> true) Then
                    Me.KategorieCenField = value
                    Me.RaisePropertyChanged("KategorieCen")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Kniha() As String
            Get
                Return Me.KnihaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KnihaField, value) <> true) Then
                    Me.KnihaField = value
                    Me.RaisePropertyChanged("Kniha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NadrizenyKontaktId() As System.Guid
            Get
                Return Me.NadrizenyKontaktIdField
            End Get
            Set
                If (Me.NadrizenyKontaktIdField.Equals(value) <> true) Then
                    Me.NadrizenyKontaktIdField = value
                    Me.RaisePropertyChanged("NadrizenyKontaktId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NazevFirmy() As String
            Get
                Return Me.NazevFirmyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NazevFirmyField, value) <> true) Then
                    Me.NazevFirmyField = value
                    Me.RaisePropertyChanged("NazevFirmy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NazevFirmy2() As String
            Get
                Return Me.NazevFirmy2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.NazevFirmy2Field, value) <> true) Then
                    Me.NazevFirmy2Field = value
                    Me.RaisePropertyChanged("NazevFirmy2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ObchodniRejstrik() As String
            Get
                Return Me.ObchodniRejstrikField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObchodniRejstrikField, value) <> true) Then
                    Me.ObchodniRejstrikField = value
                    Me.RaisePropertyChanged("ObchodniRejstrik")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Odberatel() As Boolean
            Get
                Return Me.OdberatelField
            End Get
            Set
                If (Me.OdberatelField.Equals(value) <> true) Then
                    Me.OdberatelField = value
                    Me.RaisePropertyChanged("Odberatel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PlatceDPH() As Boolean
            Get
                Return Me.PlatceDPHField
            End Get
            Set
                If (Me.PlatceDPHField.Equals(value) <> true) Then
                    Me.PlatceDPHField = value
                    Me.RaisePropertyChanged("PlatceDPH")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Pocet1() As Double
            Get
                Return Me.Pocet1Field
            End Get
            Set
                If (Me.Pocet1Field.Equals(value) <> true) Then
                    Me.Pocet1Field = value
                    Me.RaisePropertyChanged("Pocet1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Pocet2() As Double
            Get
                Return Me.Pocet2Field
            End Get
            Set
                If (Me.Pocet2Field.Equals(value) <> true) Then
                    Me.Pocet2Field = value
                    Me.RaisePropertyChanged("Pocet2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PocetZamestnancu() As String
            Get
                Return Me.PocetZamestnancuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PocetZamestnancuField, value) <> true) Then
                    Me.PocetZamestnancuField = value
                    Me.RaisePropertyChanged("PocetZamestnancu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Poznamky() As String
            Get
                Return Me.PoznamkyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PoznamkyField, value) <> true) Then
                    Me.PoznamkyField = value
                    Me.RaisePropertyChanged("Poznamky")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PrihlasovaciJmeno() As String
            Get
                Return Me.PrihlasovaciJmenoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrihlasovaciJmenoField, value) <> true) Then
                    Me.PrihlasovaciJmenoField = value
                    Me.RaisePropertyChanged("PrihlasovaciJmeno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Prijmeni() As String
            Get
                Return Me.PrijmeniField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrijmeniField, value) <> true) Then
                    Me.PrijmeniField = value
                    Me.RaisePropertyChanged("Prijmeni")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Referent() As String
            Get
                Return Me.ReferentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReferentField, value) <> true) Then
                    Me.ReferentField = value
                    Me.RaisePropertyChanged("Referent")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sablona() As String
            Get
                Return Me.SablonaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SablonaField, value) <> true) Then
                    Me.SablonaField = value
                    Me.RaisePropertyChanged("Sablona")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sleva() As Decimal
            Get
                Return Me.SlevaField
            End Get
            Set
                If (Me.SlevaField.Equals(value) <> true) Then
                    Me.SlevaField = value
                    Me.RaisePropertyChanged("Sleva")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SlevaDodavatele() As Decimal
            Get
                Return Me.SlevaDodavateleField
            End Get
            Set
                If (Me.SlevaDodavateleField.Equals(value) <> true) Then
                    Me.SlevaDodavateleField = value
                    Me.RaisePropertyChanged("SlevaDodavatele")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SplatnostFaktur() As Short
            Get
                Return Me.SplatnostFakturField
            End Get
            Set
                If (Me.SplatnostFakturField.Equals(value) <> true) Then
                    Me.SplatnostFakturField = value
                    Me.RaisePropertyChanged("SplatnostFaktur")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StavKontaktu() As String
            Get
                Return Me.StavKontaktuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StavKontaktuField, value) <> true) Then
                    Me.StavKontaktuField = value
                    Me.RaisePropertyChanged("StavKontaktu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Telefon() As String
            Get
                Return Me.TelefonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelefonField, value) <> true) Then
                    Me.TelefonField = value
                    Me.RaisePropertyChanged("Telefon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Telefon2() As String
            Get
                Return Me.Telefon2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Telefon2Field, value) <> true) Then
                    Me.Telefon2Field = value
                    Me.RaisePropertyChanged("Telefon2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TypKontaktu() As String
            Get
                Return Me.TypKontaktuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TypKontaktuField, value) <> true) Then
                    Me.TypKontaktuField = value
                    Me.RaisePropertyChanged("TypKontaktu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TypZaznamu() As String
            Get
                Return Me.TypZaznamuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TypZaznamuField, value) <> true) Then
                    Me.TypZaznamuField = value
                    Me.RaisePropertyChanged("TypZaznamu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Udaj1() As String
            Get
                Return Me.Udaj1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Udaj1Field, value) <> true) Then
                    Me.Udaj1Field = value
                    Me.RaisePropertyChanged("Udaj1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Udaj2() As String
            Get
                Return Me.Udaj2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Udaj2Field, value) <> true) Then
                    Me.Udaj2Field = value
                    Me.RaisePropertyChanged("Udaj2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Urok() As Single
            Get
                Return Me.UrokField
            End Get
            Set
                If (Me.UrokField.Equals(value) <> true) Then
                    Me.UrokField = value
                    Me.RaisePropertyChanged("Urok")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Zasilat() As String
            Get
                Return Me.ZasilatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ZasilatField, value) <> true) Then
                    Me.ZasilatField = value
                    Me.RaisePropertyChanged("Zasilat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ZpusobUhrady() As String
            Get
                Return Me.ZpusobUhradyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ZpusobUhradyField, value) <> true) Then
                    Me.ZpusobUhradyField = value
                    Me.RaisePropertyChanged("ZpusobUhrady")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property rowguid() As System.Guid
            Get
                Return Me.rowguidField
            End Get
            Set
                If (Me.rowguidField.Equals(value) <> true) Then
                    Me.rowguidField = value
                    Me.RaisePropertyChanged("rowguid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property timestamp() As Byte()
            Get
                Return Me.timestampField
            End Get
            Set
                If (Object.ReferenceEquals(Me.timestampField, value) <> true) Then
                    Me.timestampField = value
                    Me.RaisePropertyChanged("timestamp")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AdresaContract", [Namespace]:="http://www.altus.cz/Altus.COM.V12.BasicContracts/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AdresaContract
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ISOZemeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObecField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OkresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PSCField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UliceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private rowguidField As System.Guid
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ISOZeme() As String
            Get
                Return Me.ISOZemeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ISOZemeField, value) <> true) Then
                    Me.ISOZemeField = value
                    Me.RaisePropertyChanged("ISOZeme")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Obec() As String
            Get
                Return Me.ObecField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObecField, value) <> true) Then
                    Me.ObecField = value
                    Me.RaisePropertyChanged("Obec")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Okres() As String
            Get
                Return Me.OkresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OkresField, value) <> true) Then
                    Me.OkresField = value
                    Me.RaisePropertyChanged("Okres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PSC() As String
            Get
                Return Me.PSCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PSCField, value) <> true) Then
                    Me.PSCField = value
                    Me.RaisePropertyChanged("PSC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Ulice() As String
            Get
                Return Me.UliceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UliceField, value) <> true) Then
                    Me.UliceField = value
                    Me.RaisePropertyChanged("Ulice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property rowguid() As System.Guid
            Get
                Return Me.rowguidField
            End Get
            Set
                If (Me.rowguidField.Equals(value) <> true) Then
                    Me.rowguidField = value
                    Me.RaisePropertyChanged("rowguid")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ExtendedPropertyContract", [Namespace]:="http://www.altus.cz/Altus.COM.V12.BasicContracts/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ExtendedPropertyContract
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DBTypeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DBType() As Integer
            Get
                Return Me.DBTypeField
            End Get
            Set
                If (Me.DBTypeField.Equals(value) <> true) Then
                    Me.DBTypeField = value
                    Me.RaisePropertyChanged("DBType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ExceptionContract", [Namespace]:="http://www.altus.cz/Altus.COM.V12.BasicContracts/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ExceptionContract
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InnerExceptionField As ServiceReferenceAgiloKontakty.ExceptionContract
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsApplicationExceptionField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsTerminalFaultField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumberField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InnerException() As ServiceReferenceAgiloKontakty.ExceptionContract
            Get
                Return Me.InnerExceptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InnerExceptionField, value) <> true) Then
                    Me.InnerExceptionField = value
                    Me.RaisePropertyChanged("InnerException")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsApplicationException() As Boolean
            Get
                Return Me.IsApplicationExceptionField
            End Get
            Set
                If (Me.IsApplicationExceptionField.Equals(value) <> true) Then
                    Me.IsApplicationExceptionField = value
                    Me.RaisePropertyChanged("IsApplicationException")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsTerminalFault() As Boolean
            Get
                Return Me.IsTerminalFaultField
            End Get
            Set
                If (Me.IsTerminalFaultField.Equals(value) <> true) Then
                    Me.IsTerminalFaultField = value
                    Me.RaisePropertyChanged("IsTerminalFault")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Number() As Integer
            Get
                Return Me.NumberField
            End Get
            Set
                If (Me.NumberField.Equals(value) <> true) Then
                    Me.NumberField = value
                    Me.RaisePropertyChanged("Number")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Source() As String
            Get
                Return Me.SourceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceField, value) <> true) Then
                    Me.SourceField = value
                    Me.RaisePropertyChanged("Source")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BankovniSpojeniContract", [Namespace]:="http://www.altus.cz/Altus.COM.V12.BasicContracts/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BankovniSpojeniContract
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdresaBankyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BankaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BankovniSpojeniField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CisloUctuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DatumAktualizaceField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ISOZemeBankyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KodBankyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MenaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PobockaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PopisKontaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SpecifickySymbolField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VychoziField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private rowguidField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private timestampField() As Byte
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdresaBanky() As String
            Get
                Return Me.AdresaBankyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdresaBankyField, value) <> true) Then
                    Me.AdresaBankyField = value
                    Me.RaisePropertyChanged("AdresaBanky")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Banka() As String
            Get
                Return Me.BankaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BankaField, value) <> true) Then
                    Me.BankaField = value
                    Me.RaisePropertyChanged("Banka")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BankovniSpojeni() As Integer
            Get
                Return Me.BankovniSpojeniField
            End Get
            Set
                If (Me.BankovniSpojeniField.Equals(value) <> true) Then
                    Me.BankovniSpojeniField = value
                    Me.RaisePropertyChanged("BankovniSpojeni")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CisloUctu() As String
            Get
                Return Me.CisloUctuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CisloUctuField, value) <> true) Then
                    Me.CisloUctuField = value
                    Me.RaisePropertyChanged("CisloUctu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DatumAktualizace() As Date
            Get
                Return Me.DatumAktualizaceField
            End Get
            Set
                If (Me.DatumAktualizaceField.Equals(value) <> true) Then
                    Me.DatumAktualizaceField = value
                    Me.RaisePropertyChanged("DatumAktualizace")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ISOZemeBanky() As String
            Get
                Return Me.ISOZemeBankyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ISOZemeBankyField, value) <> true) Then
                    Me.ISOZemeBankyField = value
                    Me.RaisePropertyChanged("ISOZemeBanky")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property KodBanky() As String
            Get
                Return Me.KodBankyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KodBankyField, value) <> true) Then
                    Me.KodBankyField = value
                    Me.RaisePropertyChanged("KodBanky")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Mena() As String
            Get
                Return Me.MenaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MenaField, value) <> true) Then
                    Me.MenaField = value
                    Me.RaisePropertyChanged("Mena")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Pobocka() As String
            Get
                Return Me.PobockaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PobockaField, value) <> true) Then
                    Me.PobockaField = value
                    Me.RaisePropertyChanged("Pobocka")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PopisKonta() As String
            Get
                Return Me.PopisKontaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PopisKontaField, value) <> true) Then
                    Me.PopisKontaField = value
                    Me.RaisePropertyChanged("PopisKonta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SpecifickySymbol() As String
            Get
                Return Me.SpecifickySymbolField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SpecifickySymbolField, value) <> true) Then
                    Me.SpecifickySymbolField = value
                    Me.RaisePropertyChanged("SpecifickySymbol")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Vychozi() As Boolean
            Get
                Return Me.VychoziField
            End Get
            Set
                If (Me.VychoziField.Equals(value) <> true) Then
                    Me.VychoziField = value
                    Me.RaisePropertyChanged("Vychozi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property rowguid() As System.Nullable(Of System.Guid)
            Get
                Return Me.rowguidField
            End Get
            Set
                If (Me.rowguidField.Equals(value) <> true) Then
                    Me.rowguidField = value
                    Me.RaisePropertyChanged("rowguid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property timestamp() As Byte()
            Get
                Return Me.timestampField
            End Get
            Set
                If (Object.ReferenceEquals(Me.timestampField, value) <> true) Then
                    Me.timestampField = value
                    Me.RaisePropertyChanged("timestamp")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.altus.cz/Altus.COM.V12.BasicContracts/", ConfigurationName:="ServiceReferenceAgiloKontakty.IKontakty")>  _
    Public Interface IKontakty
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontakt", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktException"& _ 
            "ContractFault", Name:="ExceptionContract")>  _
        Function NacistKontakt(ByVal firma As String) As ServiceReferenceAgiloKontakty.KontaktContract
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontakt", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktResponse")>  _
        Function NacistKontaktAsync(ByVal firma As String) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.KontaktContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktPodleId", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktPodleIdRe"& _ 
            "sponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktPodleIdEx"& _ 
            "ceptionContractFault", Name:="ExceptionContract")>  _
        Function NacistKontaktPodleId(ByVal rowguid As System.Guid) As ServiceReferenceAgiloKontakty.KontaktContract
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktPodleId", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktPodleIdRe"& _ 
            "sponse")>  _
        Function NacistKontaktPodleIdAsync(ByVal rowguid As System.Guid) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.KontaktContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/AktualizovatKontakt", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/AktualizovatKontaktRes"& _ 
            "ponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/AktualizovatKontaktExc"& _ 
            "eptionContractFault", Name:="ExceptionContract")>  _
        Sub AktualizovatKontakt(ByVal kontakt As ServiceReferenceAgiloKontakty.KontaktContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/AktualizovatKontakt", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/AktualizovatKontaktRes"& _ 
            "ponse")>  _
        Function AktualizovatKontaktAsync(ByVal kontakt As ServiceReferenceAgiloKontakty.KontaktContract) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/VlozitKontakt", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/VlozitKontaktResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/VlozitKontaktException"& _ 
            "ContractFault", Name:="ExceptionContract")>  _
        Function VlozitKontakt(ByVal kontakt As ServiceReferenceAgiloKontakty.KontaktContract) As System.Guid
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/VlozitKontakt", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/VlozitKontaktResponse")>  _
        Function VlozitKontaktAsync(ByVal kontakt As ServiceReferenceAgiloKontakty.KontaktContract) As System.Threading.Tasks.Task(Of System.Guid)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetVsechKontak"& _ 
            "tu", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetVsechKontak"& _ 
            "tuResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetVsechKontak"& _ 
            "tuExceptionContractFault", Name:="ExceptionContract")>  _
        Function NacistPocetVsechKontaktu() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetVsechKontak"& _ 
            "tu", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetVsechKontak"& _ 
            "tuResponse")>  _
        Function NacistPocetVsechKontaktuAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetZmenenychKo"& _ 
            "ntaktuTimestampBytes", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetZmenenychKo"& _ 
            "ntaktuTimestampBytesResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetZmenenychKo"& _ 
            "ntaktuTimestampBytesExceptionContractFault", Name:="ExceptionContract")>  _
        Function NacistPocetZmenenychKontaktuTimestampBytes(ByVal timestamp() As Byte) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetZmenenychKo"& _ 
            "ntaktuTimestampBytes", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetZmenenychKo"& _ 
            "ntaktuTimestampBytesResponse")>  _
        Function NacistPocetZmenenychKontaktuTimestampBytesAsync(ByVal timestamp() As Byte) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetZmenenychKo"& _ 
            "ntaktuTimestampHexString", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetZmenenychKo"& _ 
            "ntaktuTimestampHexStringResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetZmenenychKo"& _ 
            "ntaktuTimestampHexStringExceptionContractFault", Name:="ExceptionContract")>  _
        Function NacistPocetZmenenychKontaktuTimestampHexString(ByVal timestampHex As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetZmenenychKo"& _ 
            "ntaktuTimestampHexString", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistPocetZmenenychKo"& _ 
            "ntaktuTimestampHexStringResponse")>  _
        Function NacistPocetZmenenychKontaktuTimestampHexStringAsync(ByVal timestampHex As String) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistVsechnyKontakty", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistVsechnyKontaktyR"& _ 
            "esponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistVsechnyKontaktyE"& _ 
            "xceptionContractFault", Name:="ExceptionContract")>  _
        Function NacistVsechnyKontakty(ByVal pageNumber As Integer, ByVal pageLength As Integer) As ServiceReferenceAgiloKontakty.KontaktContract()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistVsechnyKontakty", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistVsechnyKontaktyR"& _ 
            "esponse")>  _
        Function NacistVsechnyKontaktyAsync(ByVal pageNumber As Integer, ByVal pageLength As Integer) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.KontaktContract())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistZmeneneKontaktyT"& _ 
            "imestampBytes", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistZmeneneKontaktyT"& _ 
            "imestampBytesResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistZmeneneKontaktyT"& _ 
            "imestampBytesExceptionContractFault", Name:="ExceptionContract")>  _
        Function NacistZmeneneKontaktyTimestampBytes(ByVal pageNumber As Integer, ByVal pageLength As Integer, ByVal timestamp() As Byte) As ServiceReferenceAgiloKontakty.KontaktContract()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistZmeneneKontaktyT"& _ 
            "imestampBytes", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistZmeneneKontaktyT"& _ 
            "imestampBytesResponse")>  _
        Function NacistZmeneneKontaktyTimestampBytesAsync(ByVal pageNumber As Integer, ByVal pageLength As Integer, ByVal timestamp() As Byte) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.KontaktContract())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistZmeneneKontaktyT"& _ 
            "imestampHexString", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistZmeneneKontaktyT"& _ 
            "imestampHexStringResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistZmeneneKontaktyT"& _ 
            "imestampHexStringExceptionContractFault", Name:="ExceptionContract")>  _
        Function NacistZmeneneKontaktyTimestampHexString(ByVal pageNumber As Integer, ByVal pageLength As Integer, ByVal timestampHex As String) As ServiceReferenceAgiloKontakty.KontaktContract()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistZmeneneKontaktyT"& _ 
            "imestampHexString", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistZmeneneKontaktyT"& _ 
            "imestampHexStringResponse")>  _
        Function NacistZmeneneKontaktyTimestampHexStringAsync(ByVal pageNumber As Integer, ByVal pageLength As Integer, ByVal timestampHex As String) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.KontaktContract())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktyPodleSlo"& _ 
            "upce", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktyPodleSlo"& _ 
            "upceResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktyPodleSlo"& _ 
            "upceExceptionContractFault", Name:="ExceptionContract")>  _
        Function NacistKontaktyPodleSloupce(ByVal sloupec As String, ByVal hodnota As String, ByVal pageNumber As Integer, ByVal pageLength As Integer) As ServiceReferenceAgiloKontakty.KontaktContract()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktyPodleSlo"& _ 
            "upce", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistKontaktyPodleSlo"& _ 
            "upceResponse")>  _
        Function NacistKontaktyPodleSloupceAsync(ByVal sloupec As String, ByVal hodnota As String, ByVal pageNumber As Integer, ByVal pageLength As Integer) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.KontaktContract())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistBankovniSpojeniK"& _ 
            "ontaktu", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistBankovniSpojeniK"& _ 
            "ontaktuResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistBankovniSpojeniK"& _ 
            "ontaktuExceptionContractFault", Name:="ExceptionContract")>  _
        Function NacistBankovniSpojeniKontaktu(ByVal kontaktId As System.Guid) As ServiceReferenceAgiloKontakty.BankovniSpojeniContract()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistBankovniSpojeniK"& _ 
            "ontaktu", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/NacistBankovniSpojeniK"& _ 
            "ontaktuResponse")>  _
        Function NacistBankovniSpojeniKontaktuAsync(ByVal kontaktId As System.Guid) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.BankovniSpojeniContract())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/VlozitBankovniSpojeniK"& _ 
            "ontaktu", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/VlozitBankovniSpojeniK"& _ 
            "ontaktuResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/VlozitBankovniSpojeniK"& _ 
            "ontaktuExceptionContractFault", Name:="ExceptionContract")>  _
        Sub VlozitBankovniSpojeniKontaktu(ByVal kontaktId As System.Guid, ByVal novaBankovniSpojeni() As ServiceReferenceAgiloKontakty.BankovniSpojeniContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/VlozitBankovniSpojeniK"& _ 
            "ontaktu", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/VlozitBankovniSpojeniK"& _ 
            "ontaktuResponse")>  _
        Function VlozitBankovniSpojeniKontaktuAsync(ByVal kontaktId As System.Guid, ByVal novaBankovniSpojeni() As ServiceReferenceAgiloKontakty.BankovniSpojeniContract) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/ZmenitBankovniSpojeniK"& _ 
            "ontaktu", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/ZmenitBankovniSpojeniK"& _ 
            "ontaktuResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/ZmenitBankovniSpojeniK"& _ 
            "ontaktuExceptionContractFault", Name:="ExceptionContract")>  _
        Sub ZmenitBankovniSpojeniKontaktu(ByVal kontaktId As System.Guid, ByVal zmenenaBankovniSpojeni() As ServiceReferenceAgiloKontakty.BankovniSpojeniContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/ZmenitBankovniSpojeniK"& _ 
            "ontaktu", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/ZmenitBankovniSpojeniK"& _ 
            "ontaktuResponse")>  _
        Function ZmenitBankovniSpojeniKontaktuAsync(ByVal kontaktId As System.Guid, ByVal zmenenaBankovniSpojeni() As ServiceReferenceAgiloKontakty.BankovniSpojeniContract) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/OdstranitBankovniSpoje"& _ 
            "niKontaktu", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/OdstranitBankovniSpoje"& _ 
            "niKontaktuResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReferenceAgiloKontakty.ExceptionContract), Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/OdstranitBankovniSpoje"& _ 
            "niKontaktuExceptionContractFault", Name:="ExceptionContract")>  _
        Sub OdstranitBankovniSpojeniKontaktu(ByVal kontaktId As System.Guid, ByVal odstranovanaBankovniSpojeni() As ServiceReferenceAgiloKontakty.BankovniSpojeniContract)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/OdstranitBankovniSpoje"& _ 
            "niKontaktu", ReplyAction:="http://www.altus.cz/Altus.COM.V12.BasicContracts/IKontakty/OdstranitBankovniSpoje"& _ 
            "niKontaktuResponse")>  _
        Function OdstranitBankovniSpojeniKontaktuAsync(ByVal kontaktId As System.Guid, ByVal odstranovanaBankovniSpojeni() As ServiceReferenceAgiloKontakty.BankovniSpojeniContract) As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IKontaktyChannel
        Inherits ServiceReferenceAgiloKontakty.IKontakty, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class KontaktyClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReferenceAgiloKontakty.IKontakty)
        Implements ServiceReferenceAgiloKontakty.IKontakty
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function NacistKontakt(ByVal firma As String) As ServiceReferenceAgiloKontakty.KontaktContract Implements ServiceReferenceAgiloKontakty.IKontakty.NacistKontakt
            Return MyBase.Channel.NacistKontakt(firma)
        End Function
        
        Public Function NacistKontaktAsync(ByVal firma As String) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.KontaktContract) Implements ServiceReferenceAgiloKontakty.IKontakty.NacistKontaktAsync
            Return MyBase.Channel.NacistKontaktAsync(firma)
        End Function
        
        Public Function NacistKontaktPodleId(ByVal rowguid As System.Guid) As ServiceReferenceAgiloKontakty.KontaktContract Implements ServiceReferenceAgiloKontakty.IKontakty.NacistKontaktPodleId
            Return MyBase.Channel.NacistKontaktPodleId(rowguid)
        End Function
        
        Public Function NacistKontaktPodleIdAsync(ByVal rowguid As System.Guid) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.KontaktContract) Implements ServiceReferenceAgiloKontakty.IKontakty.NacistKontaktPodleIdAsync
            Return MyBase.Channel.NacistKontaktPodleIdAsync(rowguid)
        End Function
        
        Public Sub AktualizovatKontakt(ByVal kontakt As ServiceReferenceAgiloKontakty.KontaktContract) Implements ServiceReferenceAgiloKontakty.IKontakty.AktualizovatKontakt
            MyBase.Channel.AktualizovatKontakt(kontakt)
        End Sub
        
        Public Function AktualizovatKontaktAsync(ByVal kontakt As ServiceReferenceAgiloKontakty.KontaktContract) As System.Threading.Tasks.Task Implements ServiceReferenceAgiloKontakty.IKontakty.AktualizovatKontaktAsync
            Return MyBase.Channel.AktualizovatKontaktAsync(kontakt)
        End Function
        
        Public Function VlozitKontakt(ByVal kontakt As ServiceReferenceAgiloKontakty.KontaktContract) As System.Guid Implements ServiceReferenceAgiloKontakty.IKontakty.VlozitKontakt
            Return MyBase.Channel.VlozitKontakt(kontakt)
        End Function
        
        Public Function VlozitKontaktAsync(ByVal kontakt As ServiceReferenceAgiloKontakty.KontaktContract) As System.Threading.Tasks.Task(Of System.Guid) Implements ServiceReferenceAgiloKontakty.IKontakty.VlozitKontaktAsync
            Return MyBase.Channel.VlozitKontaktAsync(kontakt)
        End Function
        
        Public Function NacistPocetVsechKontaktu() As Integer Implements ServiceReferenceAgiloKontakty.IKontakty.NacistPocetVsechKontaktu
            Return MyBase.Channel.NacistPocetVsechKontaktu
        End Function
        
        Public Function NacistPocetVsechKontaktuAsync() As System.Threading.Tasks.Task(Of Integer) Implements ServiceReferenceAgiloKontakty.IKontakty.NacistPocetVsechKontaktuAsync
            Return MyBase.Channel.NacistPocetVsechKontaktuAsync
        End Function
        
        Public Function NacistPocetZmenenychKontaktuTimestampBytes(ByVal timestamp() As Byte) As Integer Implements ServiceReferenceAgiloKontakty.IKontakty.NacistPocetZmenenychKontaktuTimestampBytes
            Return MyBase.Channel.NacistPocetZmenenychKontaktuTimestampBytes(timestamp)
        End Function
        
        Public Function NacistPocetZmenenychKontaktuTimestampBytesAsync(ByVal timestamp() As Byte) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReferenceAgiloKontakty.IKontakty.NacistPocetZmenenychKontaktuTimestampBytesAsync
            Return MyBase.Channel.NacistPocetZmenenychKontaktuTimestampBytesAsync(timestamp)
        End Function
        
        Public Function NacistPocetZmenenychKontaktuTimestampHexString(ByVal timestampHex As String) As Integer Implements ServiceReferenceAgiloKontakty.IKontakty.NacistPocetZmenenychKontaktuTimestampHexString
            Return MyBase.Channel.NacistPocetZmenenychKontaktuTimestampHexString(timestampHex)
        End Function
        
        Public Function NacistPocetZmenenychKontaktuTimestampHexStringAsync(ByVal timestampHex As String) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReferenceAgiloKontakty.IKontakty.NacistPocetZmenenychKontaktuTimestampHexStringAsync
            Return MyBase.Channel.NacistPocetZmenenychKontaktuTimestampHexStringAsync(timestampHex)
        End Function
        
        Public Function NacistVsechnyKontakty(ByVal pageNumber As Integer, ByVal pageLength As Integer) As ServiceReferenceAgiloKontakty.KontaktContract() Implements ServiceReferenceAgiloKontakty.IKontakty.NacistVsechnyKontakty
            Return MyBase.Channel.NacistVsechnyKontakty(pageNumber, pageLength)
        End Function
        
        Public Function NacistVsechnyKontaktyAsync(ByVal pageNumber As Integer, ByVal pageLength As Integer) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.KontaktContract()) Implements ServiceReferenceAgiloKontakty.IKontakty.NacistVsechnyKontaktyAsync
            Return MyBase.Channel.NacistVsechnyKontaktyAsync(pageNumber, pageLength)
        End Function
        
        Public Function NacistZmeneneKontaktyTimestampBytes(ByVal pageNumber As Integer, ByVal pageLength As Integer, ByVal timestamp() As Byte) As ServiceReferenceAgiloKontakty.KontaktContract() Implements ServiceReferenceAgiloKontakty.IKontakty.NacistZmeneneKontaktyTimestampBytes
            Return MyBase.Channel.NacistZmeneneKontaktyTimestampBytes(pageNumber, pageLength, timestamp)
        End Function
        
        Public Function NacistZmeneneKontaktyTimestampBytesAsync(ByVal pageNumber As Integer, ByVal pageLength As Integer, ByVal timestamp() As Byte) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.KontaktContract()) Implements ServiceReferenceAgiloKontakty.IKontakty.NacistZmeneneKontaktyTimestampBytesAsync
            Return MyBase.Channel.NacistZmeneneKontaktyTimestampBytesAsync(pageNumber, pageLength, timestamp)
        End Function
        
        Public Function NacistZmeneneKontaktyTimestampHexString(ByVal pageNumber As Integer, ByVal pageLength As Integer, ByVal timestampHex As String) As ServiceReferenceAgiloKontakty.KontaktContract() Implements ServiceReferenceAgiloKontakty.IKontakty.NacistZmeneneKontaktyTimestampHexString
            Return MyBase.Channel.NacistZmeneneKontaktyTimestampHexString(pageNumber, pageLength, timestampHex)
        End Function
        
        Public Function NacistZmeneneKontaktyTimestampHexStringAsync(ByVal pageNumber As Integer, ByVal pageLength As Integer, ByVal timestampHex As String) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.KontaktContract()) Implements ServiceReferenceAgiloKontakty.IKontakty.NacistZmeneneKontaktyTimestampHexStringAsync
            Return MyBase.Channel.NacistZmeneneKontaktyTimestampHexStringAsync(pageNumber, pageLength, timestampHex)
        End Function
        
        Public Function NacistKontaktyPodleSloupce(ByVal sloupec As String, ByVal hodnota As String, ByVal pageNumber As Integer, ByVal pageLength As Integer) As ServiceReferenceAgiloKontakty.KontaktContract() Implements ServiceReferenceAgiloKontakty.IKontakty.NacistKontaktyPodleSloupce
            Return MyBase.Channel.NacistKontaktyPodleSloupce(sloupec, hodnota, pageNumber, pageLength)
        End Function
        
        Public Function NacistKontaktyPodleSloupceAsync(ByVal sloupec As String, ByVal hodnota As String, ByVal pageNumber As Integer, ByVal pageLength As Integer) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.KontaktContract()) Implements ServiceReferenceAgiloKontakty.IKontakty.NacistKontaktyPodleSloupceAsync
            Return MyBase.Channel.NacistKontaktyPodleSloupceAsync(sloupec, hodnota, pageNumber, pageLength)
        End Function
        
        Public Function NacistBankovniSpojeniKontaktu(ByVal kontaktId As System.Guid) As ServiceReferenceAgiloKontakty.BankovniSpojeniContract() Implements ServiceReferenceAgiloKontakty.IKontakty.NacistBankovniSpojeniKontaktu
            Return MyBase.Channel.NacistBankovniSpojeniKontaktu(kontaktId)
        End Function
        
        Public Function NacistBankovniSpojeniKontaktuAsync(ByVal kontaktId As System.Guid) As System.Threading.Tasks.Task(Of ServiceReferenceAgiloKontakty.BankovniSpojeniContract()) Implements ServiceReferenceAgiloKontakty.IKontakty.NacistBankovniSpojeniKontaktuAsync
            Return MyBase.Channel.NacistBankovniSpojeniKontaktuAsync(kontaktId)
        End Function
        
        Public Sub VlozitBankovniSpojeniKontaktu(ByVal kontaktId As System.Guid, ByVal novaBankovniSpojeni() As ServiceReferenceAgiloKontakty.BankovniSpojeniContract) Implements ServiceReferenceAgiloKontakty.IKontakty.VlozitBankovniSpojeniKontaktu
            MyBase.Channel.VlozitBankovniSpojeniKontaktu(kontaktId, novaBankovniSpojeni)
        End Sub
        
        Public Function VlozitBankovniSpojeniKontaktuAsync(ByVal kontaktId As System.Guid, ByVal novaBankovniSpojeni() As ServiceReferenceAgiloKontakty.BankovniSpojeniContract) As System.Threading.Tasks.Task Implements ServiceReferenceAgiloKontakty.IKontakty.VlozitBankovniSpojeniKontaktuAsync
            Return MyBase.Channel.VlozitBankovniSpojeniKontaktuAsync(kontaktId, novaBankovniSpojeni)
        End Function
        
        Public Sub ZmenitBankovniSpojeniKontaktu(ByVal kontaktId As System.Guid, ByVal zmenenaBankovniSpojeni() As ServiceReferenceAgiloKontakty.BankovniSpojeniContract) Implements ServiceReferenceAgiloKontakty.IKontakty.ZmenitBankovniSpojeniKontaktu
            MyBase.Channel.ZmenitBankovniSpojeniKontaktu(kontaktId, zmenenaBankovniSpojeni)
        End Sub
        
        Public Function ZmenitBankovniSpojeniKontaktuAsync(ByVal kontaktId As System.Guid, ByVal zmenenaBankovniSpojeni() As ServiceReferenceAgiloKontakty.BankovniSpojeniContract) As System.Threading.Tasks.Task Implements ServiceReferenceAgiloKontakty.IKontakty.ZmenitBankovniSpojeniKontaktuAsync
            Return MyBase.Channel.ZmenitBankovniSpojeniKontaktuAsync(kontaktId, zmenenaBankovniSpojeni)
        End Function
        
        Public Sub OdstranitBankovniSpojeniKontaktu(ByVal kontaktId As System.Guid, ByVal odstranovanaBankovniSpojeni() As ServiceReferenceAgiloKontakty.BankovniSpojeniContract) Implements ServiceReferenceAgiloKontakty.IKontakty.OdstranitBankovniSpojeniKontaktu
            MyBase.Channel.OdstranitBankovniSpojeniKontaktu(kontaktId, odstranovanaBankovniSpojeni)
        End Sub
        
        Public Function OdstranitBankovniSpojeniKontaktuAsync(ByVal kontaktId As System.Guid, ByVal odstranovanaBankovniSpojeni() As ServiceReferenceAgiloKontakty.BankovniSpojeniContract) As System.Threading.Tasks.Task Implements ServiceReferenceAgiloKontakty.IKontakty.OdstranitBankovniSpojeniKontaktuAsync
            Return MyBase.Channel.OdstranitBankovniSpojeniKontaktuAsync(kontaktId, odstranovanaBankovniSpojeni)
        End Function
    End Class
End Namespace
