'------------------------------------------------------------------------------
' <auto-generated>
'     Tento kód byl generován nástrojem.
'     Verze modulu runtime:4.0.30319.42000
'
'     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
'     dojde-li k novému generování kódu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference100Mega
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(Name:="I6 Web ServiceSoap", [Namespace]:="http://www.cybersoft.cz/I6/Web/WebService/", ConfigurationName:="ServiceReference100Mega.I6WebServiceSoap")>  _
    Public Interface I6WebServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cybersoft.cz/I6/Web/WebService/HelloWorld", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HelloWorld() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cybersoft.cz/I6/Web/WebService/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cybersoft.cz/I6/Web/WebService/GetResult", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetResult(ByVal resultType As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cybersoft.cz/I6/Web/WebService/GetResult", ReplyAction:="*")>  _
        Function GetResultAsync(ByVal resultType As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cybersoft.cz/I6/Web/WebService/GetResultByCode", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetResultByCode(ByVal resultType As String, ByVal code As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cybersoft.cz/I6/Web/WebService/GetResultByCode", ReplyAction:="*")>  _
        Function GetResultByCodeAsync(ByVal resultType As String, ByVal code As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cybersoft.cz/I6/Web/WebService/GetResultByFromTo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetResultByFromTo(ByVal resultType As String, ByVal from As Date, ByVal [to] As Date) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cybersoft.cz/I6/Web/WebService/GetResultByFromTo", ReplyAction:="*")>  _
        Function GetResultByFromToAsync(ByVal resultType As String, ByVal from As Date, ByVal [to] As Date) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface I6WebServiceSoapChannel
        Inherits ServiceReference100Mega.I6WebServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class I6WebServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference100Mega.I6WebServiceSoap)
        Implements ServiceReference100Mega.I6WebServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function HelloWorld() As String Implements ServiceReference100Mega.I6WebServiceSoap.HelloWorld
            Return MyBase.Channel.HelloWorld
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of String) Implements ServiceReference100Mega.I6WebServiceSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync
        End Function
        
        Public Function GetResult(ByVal resultType As String) As System.Xml.XmlNode Implements ServiceReference100Mega.I6WebServiceSoap.GetResult
            Return MyBase.Channel.GetResult(resultType)
        End Function
        
        Public Function GetResultAsync(ByVal resultType As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements ServiceReference100Mega.I6WebServiceSoap.GetResultAsync
            Return MyBase.Channel.GetResultAsync(resultType)
        End Function
        
        Public Function GetResultByCode(ByVal resultType As String, ByVal code As String) As System.Xml.XmlNode Implements ServiceReference100Mega.I6WebServiceSoap.GetResultByCode
            Return MyBase.Channel.GetResultByCode(resultType, code)
        End Function
        
        Public Function GetResultByCodeAsync(ByVal resultType As String, ByVal code As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements ServiceReference100Mega.I6WebServiceSoap.GetResultByCodeAsync
            Return MyBase.Channel.GetResultByCodeAsync(resultType, code)
        End Function
        
        Public Function GetResultByFromTo(ByVal resultType As String, ByVal from As Date, ByVal [to] As Date) As System.Xml.XmlNode Implements ServiceReference100Mega.I6WebServiceSoap.GetResultByFromTo
            Return MyBase.Channel.GetResultByFromTo(resultType, from, [to])
        End Function
        
        Public Function GetResultByFromToAsync(ByVal resultType As String, ByVal from As Date, ByVal [to] As Date) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements ServiceReference100Mega.I6WebServiceSoap.GetResultByFromToAsync
            Return MyBase.Channel.GetResultByFromToAsync(resultType, from, [to])
        End Function
    End Class
End Namespace
