'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AG_tblUsers
    Public Property IDUser As Integer
    Public Property IDRole As Integer
    Public Property UserFirstName As String
    Public Property UserLastName As String
    Public Property UserLogin As String
    Public Property UserPWD As String
    Public Property UserMobilePhone As String
    Public Property UserAccountEnabled As Boolean
    Public Property HodinovaSazba As Nullable(Of Decimal)
    Public Property VzdalenkaMalyZasah As Nullable(Of Decimal)
    Public Property VzdalenakVelkyZasah As Nullable(Of Decimal)
    Public Property ProcentoZHodinoveSazby As Nullable(Of Decimal)
    Public Property ProcentoZMaleVzdalenky As Nullable(Of Decimal)
    Public Property ProcentoZVelkeVzdalenky As Nullable(Of Decimal)
    Public Property SumaPosledniCHProvizi As Decimal
    Public Property TrelloUID As String
    Public Property TrelloPWD As String
    Public Property TrelloSloupec As String
    Public Property TrelloKey As String
    Public Property TrelloToken As String
    Public Property MenuFaktVychoziFiltr As Short
    Public Property MapVisible As Boolean
    Public Property PredkontaceProdejZbozi As String
    Public Property TechnikoviPocitameOdmeny As Boolean

End Class
