'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AG_tblSignalRUsers
    Public Property IDU As Integer
    Public Property ConnectionID As String
    Public Property Login As String
    Public Property Name As String
    Public Property Surname As String
    Public Property Lat As Decimal
    Public Property Lng As Decimal
    Public Property Color As String
    Public Property Time As Date
    Public Property OnOff As String

End Class
