'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AG_tblUsersLastPosition
    Public Property IDG As Long
    Public Property IDUser As Integer
    Public Property GPSTime As Date
    Public Property GPSLat As String
    Public Property GPSLng As String

End Class
