'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AG_tblIBBakovniUcty
    Public Property IDBankovnihoUctu As Integer
    Public Property Token As String
    Public Property NazevUctu As String

End Class
