'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AGsp_Get_DashboardPohledavkyPodrobne_Result1
    Public Property Variabilni_symbol As String
    Public Property Zbyva_uhradit As Decimal
    Public Property PoSplatnosti As Decimal
    Public Property Rok As Nullable(Of Short)
    Public Property Datum_splatnosti As Nullable(Of Date)
    Public Property Nazev_firmy As String

End Class
