'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AGvwrr_TypPolozkyPracaku
    Public Property rr_TypPolozkyPracaku As Short
    Public Property rr_TypPolozkyPracakuHodnota As String

End Class
