'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AGvw_FA_PracakySeznam
    Public Property IDVykazPrace As Integer
    Public Property DatVzniku As Date
    Public Property IDPracoviste As String
    Public Property rr_StavPracaku As Byte
    Public Property rr_StavPracakuHodnota As String
    Public Property HtmlZnacka As String
    Public Property rr_TypServisniSmlouvy As Byte
    Public Property rr_TypServisniSmlouvyHodnota As String
    Public Property CisloFaktury As String
    Public Property IDUserZalozil As Nullable(Of Integer)
    Public Property UserZalozil As String
    Public Property IDUserUpravil As Nullable(Of Integer)
    Public Property UserUpravil As String
    Public Property rr_FakturovatNaFirmu As Byte
    Public Property rr_FakturovatNaFirmuHodnota As String
    Public Property PobockaNazev As String
    Public Property FirmaNazev As String
    Public Property IDFirma As String

End Class
