'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AGvwrr_StavPracaku
    Public Property rr_StavPracaku As Short
    Public Property rr_StavPracakuHodnota As String
    Public Property HtmlZnacka As String

End Class
